services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: root
    volumes:
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    configs:
      - source: grafana_datasource
        target: /etc/grafana/provisioning/datasources/datasource.yml

configs:
  prometheus_config:
    content: |
      global:
        scrape_interval: 1s
      
      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: [ 'prometheus:9090' ]
        - job_name: 'spring-actuator'
          metrics_path: '/actuator/prometheus'
          static_configs:
            - targets: [ 'host.docker.internal:8080' ]
  grafana_datasource:
    content: |
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus:9090
          access: proxy
          isDefault: true

volumes:
  prometheus_data:
  grafana_data: