# spring
spring:
  application:
    name: s3uploadtest

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      location: C:\Users\ASUS\yubin\temp
      max-file-size: 200MB
      max-request-size: 200MB

# aws
cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_IMAGE_BUCKET}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false

# monitoring
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
server:
  tomcat:
    mbeanregistry:
      enabled: true